name = "praise-media-website"
type = "service"
account_id = ""
workers_dev = true
compatibility_date = "2024-12-16"

[build]
command = "npm run pages:build"
cwd = "./"
watch_paths = ["src/**/*.js", "src/**/*.jsx", "public/**/*"]

[build.upload]
format = "service-worker"

[[unsafe.bindings]]
name = "ASSETS"
type = "rpc"
service = "PAGES-DEFAULT-ASSETS-ENGINE"
